# Enterprise Observability Stack
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: ent-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - internal-data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: ent-kibana
    ports:
      - "5601:5601"
    networks:
      - public-access
      - internal-data
    depends_on:
      - elasticsearch

  prometheus:
    image: prom/prometheus:latest
    container_name: ent-prometheus
    networks:
      - internal-data
    ports:
      - "9091:9090"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: ent-grafana
    networks:
      - public-access
      - internal-data
    ports:
      - "3001:3000"

networks:
  public-access:
    name: ent-public-network
  internal-data:
    name: ent-secure-backend-network
